### ISSUE TITLE
Patch increment is not incrementing

### ISSUE THREAD

**Issue by eliseuborges** [PaulHatch/semantic-version#24]
Hi Guys,

How to increment patch part number? 

I would like to follow semantic version format X.Y.Z without prerelease at my tags name but when I commit my code (with or without (patch) label on message) that just increment prerelease number part and not increment patch part as default.

Is that behavior expected?

This is my action code.
```  
name: CI

on:        
  push:
    branches: [ main ]

jobs:  
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Git Semantic Version
        id: semantic_version
        uses: PaulHatch/semantic-version@v4
        with:
          short_tags: true
          tag_prefix: "v"
          format: "${major}.${minor}.${patch}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.semantic_version.outputs.version }}
          release_name: ${{ steps.semantic_version.outputs.version }}
          draft: false
          prerelease: false
```

**Comment by eliseuborges** [comment]
I think my problem was in this two lines:

```
tag_name: ${{ steps.semantic_version.outputs.version }}
release_name: ${{ steps.semantic_version.outputs.version }}
```

Looking carefully, I realized that your script is always looking for **--match=v*[0-9.]** and my tags wasn't been created with prefix "v", so I changed it for this:

```
tag_name: v${{ steps.semantic_version.outputs.version }}
release_name: v${{ steps.semantic_version.outputs.version }}
```

As a suggestion, I think that **--match** parameter should considering the value at **tag_prefix**. Example:

tag_prefix: "v" -> git describe --tags --abbrev=0 --match=**v[0-9.]**
tag_prefix: "version" -> git describe --tags --abbrev=0 --match=version[0-9.]
tag_prefix: "foo" -> git describe --tags --abbrev=0 --match=foo[0-9.]
tag_prefix: "bar -> git describe --tags --abbrev=0 --match=bar[0-9.]

**Comment by PaulHatch** [comment]
Hi @eliseuborges, yes, this is how this should work now--the match is a combination of the tag prefix and the version pattern.

https://github.com/PaulHatch/semantic-version/blob/master/index.js#L121-L122

The `releasePattern` value is then used as the `--match` parameter on line [144](https://github.com/PaulHatch/semantic-version/blob/master/index.js#L145).

You can set the `tag_prefix` input to an empty string to use plain tags like `1.0.0`.

**Comment by eliseuborges** [comment]
Hey Paul, 

Could you please have a look at this: **https://github.com/eliseuborges/PaulHatch-semantic-version/runs/1914416554?check_suite_focus=true**. 

On my ci.yml I don't have tag_prefix but I'm still receiving this: "The command 'git describe --tags --abbrev=0 --match=v*[0-9.] 6729b655701ea2ed3fd2fffdd24ee0aa08906271~1' failed: Error: The process '/usr/bin/git' failed with exit code 128"

**Comment by PaulHatch** [comment]
The default value for this input is `v`, you need to explicitly set the value to empty, you can see the input value in the logs:

<img width="1201" alt="Screen Shot 2021-02-16 at 5 44 27 PM" src="https://user-images.githubusercontent.com/1835615/108131343-1f1bb880-707f-11eb-83c8-1022f8de4af1.png">

That git error is just logged for reference, it means that no matching tags were found. This results in the friendlier warning about "No tags present".

**Comment by eliseuborges** [comment]
Ohhhh sorry about that. I didn't see this logs.
Thanks a lot for you time and again, congrats for this plugin.

You can considering this issue close. = )
